---
title: "SOA Challenge"
author: "Lai Wei"
date: "2023-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

# Load Packages
```{r load_packages, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(stats)
library(factoextra)
library(fitdistrplus)
library(glmnet)
```


# Import & View data
```{r , results='hide'}
raw_data <- read.csv("hazard.csv")
# to store the original data as data to avoid any mistakes in future 
data <- raw_data 

#assume 2020 
fata_amount <- 4760884
Injury_amount <- 203910


```

```{r Data Cleaning}
#convert both injuries and fatalities into amounts
#data[8:9] <- sapply(data[8:9],as.numeric) 

data <- data %>% mutate(Fatalities_amt = fata_amount*Fatalities,
                        Injury_amt = Injury_amount*Injuries,
                        total_cost = fata_amount*Fatalities + Injury_amount*Injuries + OnLevel.PD)

#removed data before 1970 
data <- data %>% filter(Year > 1969)  %>%
                 mutate(Fatalities_scale = scale(Fatalities_amt),
                        Injuries_scale = scale(Injury_amt),
                        OnLevel.PD_scale = scale(OnLevel.PD)) %>% 
                 arrange(desc(OnLevel.PD))

#remove the first 2 outliers
data_ <- data[-c(1:2),]

# Compute the correlation matrix
cor_matrix <- cor(data_[,c("Fatalities", "Injuries", "OnLevel.PD")])

# Print the correlation matrix
title <- "Correlation Matrix of Fatality, Injury, and onlevelled Property Damage"
cat("\n", title, "\n")
print(cor_matrix)
```


```{r K-means to group data into 3 categories}
k_mean_region <- function(data, r, k = 3, damage){
    
    if (r == 0) {
          d <- data %>% dplyr::select(Fatalities_scale ,Injuries_scale, damage)
    } else {
          d <- data %>% filter(Region == r) %>%
                        dplyr::select(Fatalities_scale ,Injuries_scale, damage)
    }

    set.seed(1000)
    
    hazard_kmeans <- kmeans(d, centers = k)
    f <- fviz_cluster(hazard_kmeans, data = d)
    hazard_clustered <- data %>% mutate(Cluster = factor(hazard_kmeans$cluster))
    
    return(list(visual = f, outp = hazard_clustered))
}
```


```{r K-means to find}
#visualize original property damage 

#visualize on-levelled property damage 
out = k_mean_region(data_, r=0, damage = "OnLevel.PD_scale")

data_o = out$outp
print(out$visual)
print(summary(out$outp))

data_o <- data_o %>% mutate(Type = ifelse(Cluster == 1, "Minor", ifelse(Cluster == 2, "Medium", "Major"))) %>% 
                   dplyr::select(-Cluster)

print(table(data_o$Type))

#write_csv(as.data.frame(data_o[,-c(11:12,14:16)]), "~/R output - DataWithType.csv")

```

```{r empirical_distribution}
PD_epdf <- function(data, r){
      data <- data %>% filter(total_cost > 0)
     # print(data)
      if (r == 0) {
          d <- data
      } else {
          d <- data %>% filter(Region == r)}
      print(d)
      g = ggplot(d, aes(x = total_cost)) +
           geom_density() +
           scale_x_continuous(limits = c(0, 1000000))+
           theme(plot.title = element_text(hjust = 0.5, face = "bold"))
      return(g)
}
print(PD_epdf(data = data_o, r = 0))
```


```{r fit GLM}
data_glm <- data_o %>% dplyr::select(total_cost, Region, Quarter, Year, Hazard.Group, Type) %>% 
                       filter(total_cost > 0)

data_glm[c(2:3,5:6)] <- sapply(data_glm[c(2:3,5:6)], factor)

# fit gamma with lasso component
x <- model.matrix(total_cost~., data = data_glm)
y <- data_glm$total_cost 
glm_elastic <- cv.glmnet(x,log(y), data=data_glm, family=Gamma(link = "log"), alpha =1, nfolds = 5)
r2 <- coef(glm_elastic, s = glm_elastic$lambda.min)

#write_csv(output, "/Users/Lai_Pro_2021/Desktop/R output - glm.csv")

```

```{r project future inflation using ARIMA}

inflation <- read.csv("inflation.csv")
ts.inf <- ts(inflation$Inflation, start=c(1960,1), frequency=1)
m<-matrix(2,2,data=c(1,2,1,3))
layout(m)
ts.plot(inflation$Inflation,main="Inflation from 1960 to 2021",ylab="Inflation rate")
acf(inflation$Inflation,main="")
pacf(inflation$Inflation ,main="")

#Diagnostic checking
tsdiag(inf_ar1)

#prediction 
inf_ar1 <- arima(inflation$Inflation,order=c(1,0,0))
project_inf <- predict(inf_ar1,n.ahead=129)
project_inf <- ts(project_inf$pred, start=c(2022,1), frequency=1)


#forecasting
ts.plot(ts.inf, xlim = c(1960,2150), main="Inflation from 1960 to 2021 and future projection",ylab="Inflation rate")
lines(project_inf, col = "red")


future_inflation <- data.frame(Year = seq(2022,2021+length(project_inf)),
           Inflation = as.array(project_inf))

#write.csv(future_inflation, "~/R output - future inflation projection.csv")

``` 



